export const GAME_DIRECTION_UPWARD   = 'GAME_DIRECTION_UPWARD'
export const GAME_DIRECTION_FORWARD  = 'GAME_DIRECTION_FORWARD'
export const GAME_DIRECTION_DOWNWARD = 'GAME_DIRECTION_DOWNWARD'
export const GAME_DIRECTION_BACKWARD = 'GAME_DIRECTION_BACKWARD'
export const GAME_DIRECTIONS         = [
    GAME_DIRECTION_UPWARD,
    GAME_DIRECTION_FORWARD,
    GAME_DIRECTION_DOWNWARD,
    GAME_DIRECTION_BACKWARD,
]